version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    networks:
      default:
        aliases:
          - webapi
  client-node:
    image: ${DOCKER_REGISTRY-}client-node
    build:
      context: Client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      SERVER_HOST: 'webapi:443'
    volumes:
      - ${APPDATA}/ASP.NET/Https:C:\app\Https:ro