services:
  webapi:
    build:
      context: D:\tt\SimpleWindowsDockerCompose\WebApi
      dockerfile: Dockerfile
      labels:
        com.microsoft.created-by: visual-studio
        com.microsoft.visual-studio.project-name: WebApi
      target: base
    container_name: WebApi
    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus
      /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646 /LogDebuggeeOutputToStdOut
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS: "true"
      ASPNETCORE_URLS: https://+:443;http://+:80
      DOTNET_USE_POLLING_FILE_WATCHER: '1'
      NUGET_FALLBACK_PACKAGES: ''
      NUGET_PACKAGES: C:\.nuget\packages
    image: webapi:dev
    labels:
      com.microsoft.visualstudio.debuggee.arguments: ' --additionalProbingPath c:\.nuget\packages  "C:\app\bin\Debug\net5.0\WebApi.dll"'
      com.microsoft.visualstudio.debuggee.killprogram: C:\remote_debugger\x64\utils\KillProcess.exe
        dotnet.exe
      com.microsoft.visualstudio.debuggee.program: '"C:\Program Files\dotnet\dotnet.exe"'
      com.microsoft.visualstudio.debuggee.workingdirectory: C:\app
    ports:
    - published: 5000
      target: 80
    - published: 5001
      target: 443
    volumes:
    - C:\Users\mildronize\AppData\Roaming\ASP.NET\Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro
    - C:\Users\mildronize\AppData\Roaming\Microsoft\UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
    - D:\tt\SimpleWindowsDockerCompose\WebApi:C:\app:rw
    - C:\Users\mildronize\onecoremsvsmon\16.11.1196.0:C:\remote_debugger:ro
    - D:\tt\SimpleWindowsDockerCompose\WebApi:C:\src:rw
    - C:\Users\mildronize\.nuget\packages:c:\.nuget\packages:ro
version: '3.4'